### ISSUE TITLE
Error in Garmin instructions?

### ISSUE THREAD

**Issue by MacL3an** [der-stefan/OpenTopoMap#267]
Hi! I just tried following the Garmin instructions (https://github.com/der-stefan/OpenTopoMap/blob/master/garmin/README.md), which in my case includes setting the `DATA` variable to `/Users/maclean/Downloads/opentopomap/OpenTopoMap/garmin/data/6324*.pbf` and I seem to fail at the last step. When I do:
```
java -jar $MKGMAPJAR -c $OPTIONS --style-file=$STYLEFILE \
    --precomp-sea=$SEA \
    --output-dir=output --bounds=$BOUNDS $DATA $TYPFILE
```

I get:
```
Time started: Mon Dec 28 01:18:34 CET 2020
SEVERE (Main): /Users/maclean/Downloads/opentopomap/OpenTopoMap/garmin/data/6324*.pbf: input file '/Users/maclean/Downloads/opentopomap/OpenTopoMap/garmin/data/6324*.pbf' doesn't exist
Number of MapFailedExceptions: 0
Exception in thread "main" java.lang.NullPointerException
        at uk.me.parabola.mkgmap.main.Main.endOptions(Main.java:609)
        at uk.me.parabola.mkgmap.CommandArgsReader.readArgs(CommandArgsReader.java:125)
        at uk.me.parabola.mkgmap.main.Main.mainStart(Main.java:144)
        at uk.me.parabola.mkgmap.main.Main.main(Main.java:115)
```

And when I look in the folder ` /Users/maclean/Downloads/opentopomap/OpenTopoMap/garmin/data/` there are lots of files beginning with '6324', e.g. 63240001.osm.pbf etc. 

Is there anything obvious I'm doing wrong?

**Comment by MacL3an** [comment]
When I put both the install parts and the country specific parts of the instructions in the same shell script everything worked, so my fault.
