### ISSUE TITLE
Opentopomap Garmin Asia tiles corrupt

### ISSUE THREAD

**Issue by sirwatchalot** [der-stefan/OpenTopoMap#312]
all Asia tiles at https://garmin.opentopomap.org/#asia are showing as 5.9k and coutour files look huge compared to other areas. 
The other regions don't have the same issue

**Comment by der-stefan** [comment]
The splitter does not proceed:
`Warning: No solution found for partition (-13.0517578125,16.2158203125) to (82.529296875,180.0) with 1,645,110,376 nodes
uk.me.parabola.splitter.SplitFailedException: Failed to find a correct split
	at uk.me.parabola.splitter.solver.SplittableDensityArea.split(SplittableDensityArea.java:159)
	at uk.me.parabola.splitter.solver.SplittableDensityArea.split(SplittableDensityArea.java:203)
	at uk.me.parabola.splitter.solver.AreasCalculator.calcAreas(AreasCalculator.java:226)
	at uk.me.parabola.splitter.Main.split(Main.java:227)
	at uk.me.parabola.splitter.Main.start(Main.java:121)
	at uk.me.parabola.splitter.Main.main(Main.java:81)
`
No idea what happened there.

**Comment by sirwatchalot** [comment]
is it likely to get fixed?

**Comment by sirwatchalot** [comment]
> The splitter does not proceed: `Warning: No solution found for partition (-13.0517578125,16.2158203125) to (82.529296875,180.0) with 1,645,110,376 nodes uk.me.parabola.splitter.SplitFailedException: Failed to find a correct split at uk.me.parabola.splitter.solver.SplittableDensityArea.split(SplittableDensityArea.java:159) at uk.me.parabola.splitter.solver.SplittableDensityArea.split(SplittableDensityArea.java:203) at uk.me.parabola.splitter.solver.AreasCalculator.calcAreas(AreasCalculator.java:226) at uk.me.parabola.splitter.Main.split(Main.java:227) at uk.me.parabola.splitter.Main.start(Main.java:121) at uk.me.parabola.splitter.Main.main(Main.java:81) ` No idea what happened there.

Any update on if/when this will be fixed?

**Comment by bruce55** [comment]
Looks like the files are no longer empty now.
I tried China and Japan, however the labels are now in Chinese Pinyin, which is extremely weird for Japan.

**Comment by knowacki** [comment]
Unfortunately, the issue with the maps has occurred again. All maps of Asia are corrupted.
